### ISSUE TITLE
Please put a Youtube video on the website

### ISSUE THREAD

**Issue by christhomas** [sambridhadhikari/sambridh.com#2]
We want to add a youtube video of one of the characters onto the website, so it makes it a bit more exciting.

You can find information about adding youtube videos, using this web page.

https://www.w3schools.com/html/html_youtube.asp

**Comment by sambridhadhikari** [comment]
OK

**Comment by christhomas** [comment]
A simple example, might be like this

```
<iframe width="420" height="315"
src="https://www.youtube.com/embed/tgbNymZ7vqY">
</iframe>
```

**Comment by christhomas** [comment]
When you do a task and put it onto github, please come here and comment that you've completed it so I can check your work :D

**Comment by sambridhadhikari** [comment]
DONE NOW WHAT NEXT
~~~~~
````~~~~~~
~~~~
