### ISSUE TITLE
Add some colours and different sizes to some of the text

### ISSUE THREAD

**Issue by christhomas** [sambridhadhikari/sambridh.com#3]
Hey sambridh,

So I think our next work would be to add some colours and text sizes to some of the characters so you can learn about the css rules that are needed to do this kind of thing.

In your CSS rules, you have rules that are like this
```
font-weight: bold
font-size: 12px
color: red
```

the `color` css style can take english names like "red", "purple", "green", "blue", but you can also use a computer notation like `#00AACC` but to know what those mean, takes another lesson together cause I have to explain what `hex notation` is.

`Notation`, just means a way to describe something. So it's just another way of saying "format", it's a way to describe something to the computer so it can understand it.

So the css rules are quite simple, but they affect how the website shows the text on the web page. 

```
font-weight: bold
```

just makes the text bolder and more visible

Then if you want to change the font size, you can use rules like this, here are three examples
```
font-size: 12px;
font-size: 1rem;
font-size: 200%;
```

if you use a value like `12px` then you have a number of pixels, you can put something like `120px` or `78px` if you like, it's up to you to choose depending on how big you want it to be

can you choose some css styles in your webpage and add some of these rules and see how it affects the font size or color and show me a demonstration. Make some text bigger like title text and make some text smaller because it's less important.

choose some colors and see if you understand how to apply the colors to different elements on the page.

**Comment by sambridhadhikari** [comment]
ok will do
~~~~~~~
~~
~
~
~
~
~
~
|

**Comment by sambridhadhikari** [comment]
ddone]

**Comment by christhomas** [comment]
I wrote this into discord, but I'll write it here too so you can see it easier.

Can you update some of the titles to use bigger fonts, try 72px and then choose another title and put it to 36px.

Then can you make some titles different colours, not just red. Try green, or blue

Thanks

**Comment by sambridhadhikari** [comment]
I DONT GET IT

**Comment by christhomas** [comment]
ok, I think you've changed the colours and fonts. So we can close this and open a new homework
